config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "homes#index"
  resources :friendships
 resources :posts do
  resources :comments
  resources :likes
 end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
       if user.admin?
       can :manage, :all
      else
         can :manage, Post, user: user
         can :read, :all
     end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user 
  belongs_to :post
  has_many :images, as: :imageable
 

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  attr_accessible :friend_id, :user_id
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :images, as: :imageable
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :images, as: :imageable
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"  
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user  
   
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :avatar

  def avatar_thumbnail
    if avatar.attached?   
      avatar.variant(resize: '120x120!').processed 
    else
      "/default_profile.jpg"
    end
  end

  def username
    return self.email.split('@')[0].capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar]) 

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments= Comment.all
  end
  def new
    @post=Post.find(params[:post_id])
    @comment= Comment.new
    @comment.post= @post
  end
 
  def show
    @comment= comment.find(params[:id])
  end 

  def create
    
    @post=Post.find(params[:post_id])
    @comment=current_user.comments.new(comment_params)
    @comment.post= @post  
    if @comment.save

      redirect_to post_path(@post)
    else
      render :new
    end
  end
  
  def destroy
    @post= Post.find(params[:post_id])
    @comment= @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:body, :commenter)
    end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	 before_action :find_friendship, only: [:destroy]

	def new
		@friendship= Friendship.new
    end

  	def create  
    	@friendship = current_user.friendships.new(:friend_id => params[:friend_id], friendship_status: false )  
    	if @friendship.save  
      		flash[:notice] = "Added friend."  
      		redirect_to users_path  
    	else  
      		flash[:notice] = "Unable to add friend."  
      		redirect_to users_path
    	end  
  	end 

  	

  	def destroy
   	 if @friendship_id
      @friendship_id.destroy
      flash[:success] = 'Friendship request canceled'
      redirect_to users_path
    else
      flash[:danger] = 'Friendship request not canceled'
    end
  end

  private

  def find_friendship
    @friendship_id = Friendship.find(params[:id])
  end

  	
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :find_post
	before_action :find_like, only: [:destroy]
  
  def create
    if already_liked?
    	flash[:notice] = "You can't like more than once"
  	else
    	@post.likes.create(user_id: current_user.id)
  	end
    redirect_to post_path(@post)
  end
  
  def destroy
	  if !(already_liked?)
	    flash[:notice] = "Cannot unlike"
	  else
	    @like.destroy
	  end
	  redirect_to post_path(@post)
  end

  private
  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end

  def already_liked?
  Like.where(user_id: current_user.id, post_id:
  params[:post_id]).exists?
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :set_post, only: %i[ destroy ]
  load_and_authorize_resource
  before_action :authenticate_user!,except: [:index]

  def index
    @posts= Post.all
  end
  
  def show
    @post= Post.find(params[:id])
  end

  def new
    @post= Post.new
  end

  def create
    @post= current_user.posts.new(post_params)
      if @post.save
        redirect_to posts_path
      else
        render :new
      end
  end

  def edit
    @post= Post.find(params[:id])
  end

  def update
    @post=Post.find(params[:id])
    if
      @post.update(post_params)
      redirect_to posts_path
    else
      render:edit
       
     end 
  end 
      
  def destroy
    @post.destroy
    redirect_to posts_path
  end
  
  private 
  def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:post_description, :image, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
    <p>
      <strong>body:</strong>
      <%= comment.body %>
    </p>

     <p>
      <strong>commenter:</strong>
      <%= comment.commenter %>
    </p>
    

app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build] do |f| %>
   <p>
      <%= f.label :body %>
      <br>
      <%= f.text_field :body %>
    </p>

     <p>
       <%= f.label :commenter %>
       <br>
       <%= f.text_field :commenter %>
     </p>
     <p>
       <%= f.submit %>
     </p>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<p>
	<h2>List of comments</h2>
	<%= render @post.comments %>
</p>
<p>
	<h2>Add comment</h2>
	<%= render 'comments/form' %>
</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/friendships/index.html.erb
<%= link_to 'Add Friend', friendships_path(friendship: {friend_id: @user.id, user_id: current_user.id}), method: :post%>

<% if friendship.status == "pending" %> 

    <%= link_to 'Accept', friendship, friendship:{status: "accepted"}, method: :patch %>
    
    <% elsif friendship.status == "accepted" && friendship.friend == current_user %>

    <%= link_to 'Delete', friendship, friendship:{user_id: friendship.friend, friend_id: current_user }, method: :delete, data: { confirm: 'Are you sure?' } %>

    <% elsif friendship.status == "accepted" && friendship.user == current_user %>

    <%= link_to 'Delete', friendship, friendship:{user_id: current_user, friend_id: friendship.friend },  method: :delete, data: { confirm: 'Are you sure?' } %>

    <% else %> <!-- if sending friendship request -->
    
    <%= link_to 'Delete', friendship, friendship:{user_id: current_user, friend_id: friendship.friend}, 
        method: :delete, data: { confirm: 'Are you sure?' } %>
 
<% end %> 


  

app/views/homes/index.html.erb
<h1>Welcome to Metabook Lite</h1>

<% if user_signed_in? %>

		<h3>Signed in with: <%= current_user.first_name %> <%= current_user.last_name %>	
		<h3><%= link_to"post", new_post_path %></h3>
		 <h3><%= link_to "Add Friend", root_path %></h3>
		<h3><%= link_to"SignOut", destroy_user_session_path, method: :delete%></h3>
		<h3><%= link_to"edit account", edit_user_registration_path %></h3>
		<br/>
		<%= image_tag(current_user.avatar_thumbnail) if current_user.avatar.attached? %>
		<h5> Your Profile</h5>
	<% else %>
		<h3><%= link_to"SignUp",new_user_registration_path %></h3>
                       or
		<h3><%= link_to"SignIn",new_user_session_path %></h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "style.css"%>
  </head>

  <body>
  <p class="notice"><%= notice %></p>

  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/create.js.erb
$('#post new').remove();
$('#post a').show();s

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= form_with(model: @post) do |f| %>
	<div>
		<%= f.label :post_description %><br>
	</div>
	<div>
		<%=f.text_field :post_description %><br>
	</div>
	<%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<table style="width:100%" border="2" cellspacing="20">
	 
	<h1>List of all Posts</h1>
		<thead>
			<th>Post Description</th>
			<th>Action</th>
			<th>Comment</th>
			<th>Like or Unlike</th>
		</thead>
	
		<% @posts.each do |post| %>
			<tr>
				<td><%= post.post_description %></td>
				<td><%= link_to 'show',post_path(post), class: "btn btn-info" %>
					<%= link_to 'edit', edit_post_path(post), class: "btn btn-success" %>
					<%= link_to 'delete', post, method: :delete, data:{ confirm: "are you sure to delete"}, class: "btn btn-danger" %>
				</td>
				<td><%= link_to "comment", new_post_comment_path(post), class: "btn btn-primary" %></td>
				<td>					
					<%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%>
		
		            <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>		
		            <% if pre_like %>
		              <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete, class: "btn btn-primary" %>
		            <% else %>
		              <%= button_to 'Like', post_likes_path(post), method: :post, class: "btn btn-primary" %>
					<% end %>	
				</td>

			</tr>			
		<% end %>		
</table>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>



	

app/views/posts/new.html.erb
<h2>Add a post</h2>
<%= form_with(model: @post) do |f| %>
	
	<div class="field">
		<%= f.label :post_description %><br>
	</div>
	<div class="field">
		<%=f.text_field :post_description %><br>
	</div>
	<div class="field">
		<%= f.submit %> 
	</div>
	<% link_to 'Back', posts_path %>
<% end %>

app/views/posts/show.html.erb
<p>
  <strong>Description:-</strong>
  <%= @post.post_description %>
</p>

  <%= link_to 'edit', edit_post_path(@post) %> 
  <%= link_to 'Back', posts_path %>
  <%= button_to 'Like', post_likes_path(@post), method: :post %>
  <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
 
  
    <h2>Comments</h2>
    <%=  render @post.comments %>

    <h2>Add comment</h2>
    <%= render 'comments/form' %>

  <% if user_signed_in? %>
    <%= link_to"SignOut", destroy_user_session_path, method: :delete%><br>
  <% end %>